Hm21
floriangeyer21/internet-shop pull request #6
Opened 2020-09-13 12:58 UTC by floriangeyer21

2020-09-13 16:04 UTC, margarita-ignatieva commented on src/main/java/com/internet/shop/controllers/order/CancelingOrderController.java
> +        Long userId = Long.valueOf(id);*/
Why do you use comments here?

2020-09-13 16:07 UTC, margarita-ignatieva approved these changes

2020-09-14 11:43 UTC, KseniiaMakarova requested changes

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/CancelingOrderController.java
> +public class CancelingOrderController extends HttpServlet {
the user can't cancel the order after it is completed
let's remove this controller

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/CreateOrderController.java
> +        Long userId = Long.valueOf(id);*/
remove the comments from everywhere

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/DeleteOrderForAdminController.java
> +@WebServlet("/order/delete")
```suggestion
@WebServlet("/orders/delete")
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/DeleteOrderForAdminController.java
> +public class DeleteOrderForAdminController extends HttpServlet {
```suggestion
public class DeleteOrderController extends HttpServlet {
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/DeleteOrderForAdminController.java
> +        orderService.delete(USER_ID);
why USER_ID and not orderId?

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetAllOrdersForAdminController.java
> +public class GetAllOrdersForAdminController extends HttpServlet {
```suggestion
public class GetAllOrdersController extends HttpServlet {
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetOrdersDetailController.java
> +@WebServlet("/order/getDetail")
```suggestion
@WebServlet("/orders/info")
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetOrdersDetailController.java
> +public class GetOrdersDetailController extends HttpServlet {
```suggestion
public class GetOrderDetailsController extends HttpServlet {
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetOrdersDetailController.java
> +        Order order = orderService.getById(USER_ID);
same here - why USER_ID?

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetOrdersForUserController.java
> +public class GetOrdersForUserController extends HttpServlet {
```suggestion
@WebServlet("/user/orders")
public class GetAllUserOrdersController extends HttpServlet {
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/product/GetAllProductsForAdminController.java
> +public class GetAllProductsForAdminController extends HttpServlet {
```suggestion
@WebServlet("/products/manage")
public class ManageProductsController extends HttpServlet {
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/product/GetAllProductsForUsersController.java
> +public class GetAllProductsForUsersController extends HttpServlet {
```suggestion
public class GetAllProductsController extends HttpServlet {
```

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/user/DeleteUsersController.java
> +        shoppingCartService.delete(shoppingCart.getId());*/
why have you commented this?
your shopping cart should be deleted with the user

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/model/Order.java
> +    private Double price;
please remove this field
we should not store this in Order - we will have trouble when we will connect to the DB

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/service/impl/OrderServiceImpl.java
> +        order.setPrice(price);
let's remove this

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/order/allOrdersForAdmin.jsp
> +        <th>Price</th>
let's remove `Price` column

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/order/allOrdersForAdmin.jsp
> +</html>
add a blank line to the end

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/order/allUserOrders.jsp
> +        <th>Canceling</th>
let's remove `price` and `canceling` columns

2020-09-14 11:43 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/product/all-for-admin.jsp
> +</html>
empty line

2020-09-14 16:10 UTC, KseniiaMakarova requested changes

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/CreateOrderController.java
> +@WebServlet("/order/create")
```suggestion
@WebServlet("/orders/create")
```

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/DeleteOrderController.java
> +        orderService.delete(ORDER_ID);
can you explain please why are you receiving userId as request parameter
where do you use it and why is orderId hardcoded?

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetAllOrdersController.java
> +@WebServlet("/order/all-for-admin")
```suggestion
@WebServlet("/orders")
```

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/order/GetOrderDetailsController.java
> +        Order order = orderService.getById(ORDER_ID);
let's receive orderId as a request parameter here

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/product/AddProductController.java
> +        resp.sendRedirect(req.getContextPath() + "/product/all-for-admin");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/products/manage");
```

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/controllers/product/DeleteProductController.java
> +        resp.sendRedirect(req.getContextPath() + "/product/all-for-admin");
```suggestion
        resp.sendRedirect(req.getContextPath() + "/products/manage");
```
after changing the mapping be sure that you updated it everywhere you used it

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/order/allOrdersForAdmin.jsp
> +                <a href="${pageContext.request.contextPath}/orders/info">Detail</a>
add a param here

2020-09-14 16:10 UTC, KseniiaMakarova commented on src/main/webapp/WEB-INF/views/order/allUserOrders.jsp
> +                <a href="${pageContext.request.contextPath}/orders/info">Detail</a>
same

2020-09-14 17:18 UTC, KseniiaMakarova approved these changes

2020-09-14 19:50 UTC, merged