added solution
floriangeyer21/internet-shop pull request #7
Opened 2020-09-14 21:29 UTC by floriangeyer21

2020-09-14 21:35 UTC, DariaPikul requested changes

2020-09-14 21:35 UTC, DariaPikul commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +        if (userFromDB.getPassword().equals(password)) {
```suggestion
                new AuthenticationException("Incorrect users name or password"));
        if (userFromDB.getPassword().equals(password)) {
```

2020-09-14 21:35 UTC, DariaPikul commented on src/main/webapp/WEB-INF/views/login.jsp
> +        .body1 {
```suggestion
        }
        .body1 {
```

2020-09-14 21:35 UTC, DariaPikul commented on src/main/webapp/WEB-INF/views/login.jsp
> +        <label for="psw"><b>Password</b></label>
```suggestion
        <input type="text" placeholder="Enter login" name="login" required="required" value=${login}>
        <label for="psw"><b>Password</b></label>
```

2020-09-14 21:35 UTC, DariaPikul commented on src/main/webapp/WEB-INF/views/login.jsp
> +        <button type="submit" class="/login">Sign in</button>
```suggestion
        <hr>
        <button type="submit" class="/login">Sign in</button>
```

2020-09-14 21:35 UTC, DariaPikul commented on src/main/webapp/WEB-INF/views/login.jsp
> +<div class="font">
```suggestion
</form>
<div class="font">
```

2020-09-14 21:35 UTC, DariaPikul commented on src/main/webapp/WEB-INF/views/login.jsp
> +
```suggestion
</html>
```

2020-09-15 07:27 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/controllers/LoginController.java
> +            session.setAttribute("user_id", user.getId());
let's make user_id a constant

2020-09-15 07:27 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/controllers/user/GetAllUsersController.java
> +    private static final String USER_ID = "user_id";
you are not using it here

2020-09-15 07:27 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/security/AuthenticationService.java
> +            throws com.internet.shop.exceptions.AuthenticationException;
let's use import

2020-09-15 07:27 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +        } else {
do you need else after return?

2020-09-15 07:27 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +        if (userFromDB.getPassword().equals(password)) {
either make both checks in if() or make exception message a constant

2020-09-15 09:31 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/controllers/user/GetAllUsersController.java
> +    private static final String USER_ID = "user_id";
?

2020-09-15 09:31 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +            User userFromDB = userService.findByLogin(login).get();
you are calling findByLogin() three times. Search through a database it's an expensive operation, let's save the result to local variable

2020-09-15 13:11 UTC, dmytro-hryhoruk commented on src/main/java/com/internet/shop/controllers/user/GetAllUsersController.java
> +    private static final String USER_ID = "user_id";
@floriangeyer21 do you need this constant here?

2020-09-15 14:58 UTC, dmytro-hryhoruk approved these changes

2020-09-16 05:41 UTC, merged